services:
  lb:
    build: .
    container_name: lb
    hostname: lb
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - CPU_UTIL=20-30
      - MEM_UTIL=15
      - NETTEST_TIMER=1800
